// <auto-generated />
namespace BookstoreLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createdStoreEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdStoreEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202209141624441_createdStoreEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
